### ISSUE TITLE
secure_js_login.js: Uncaught SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by vladyslav2** [jedie/django-secure-js-login#4]
Javascript error, when i open /secure_login/ page 

file secure_js_login.js 
error line: function pbkdf2(txt, salt, iterations, callback, bytes=PBKDF2_BYTE_LENGTH) {

i think you should use 
if bytes === 'undefined' => bytes = PBKDF2_BYTE_LENGTH
something like this

**Comment by jedie** [comment]
Oh, yes. "default parameters" is new and not well supported, see: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Functions/Default_parameters#Browser_compatibility

And i run the unittest only with firefox, because it's hard to activate it in travis-ci, see: https://github.com/travis-ci/travis-ci/issues/938

Thanks for reporting!

**Comment by vladyslav2** [comment]
Thanks for your application jedle
you are welcome !
